## Fluídos Conformes

Código para testear la estabilidad alrededor de una solución de equilibrio.

Lo que hacemos es tomar el jacobiano del flujo,

$\frac{\partial F^i}{\partial f^j}$ donde $f^j$ son las variables no conservativas para las cuales tenemos las expresiones del Flujo. 
A estas las multiplicamos por $[\frac{\partial c^k}{\partial f^j}]^{-1}$.
Tenemos así 

$$
P^i{}_j := \frac{\partial F^i}{\partial c^j}.
$$

Evaluamos todo en el vector $(-1,0,0,0,0)$ o sea estamos en el frame con velocidad cero y todas las variables fuera de equilibrio también cero.

Lo mismo hacemos con la fuente. 
Tenemos así el sistema linearizado en el punto de equilibrio en las variables conservativas. Multiplicamos $P^i{}_j$ por un número complejo cualquiera y para todos ellos los autovalores debieran tener parte real negativa o nula. Pero no es así...

In [1]:
using Symbolics
using LinearAlgebra

In [2]:
function Flux(flu,par)
    χ = par
    #flux = zeros(5)
    μ = flu[1]  
    T = (abs(μ))^(-1//2) 
    v = flu[2]
    x1 = flu[3]
    x2 = flu[4]
    x3 = flu[5]
    χ₀ = χ[1]
    χ₁ = χ[2]
    χ₂ = χ[3]
    γ = (1 - v^2)^(-1//2)
    τ = 2χ₁ * x3 * T / (γ*μ^3) + 24χ₂*(1//2*(1-v^2)x3^2 + 14//3 * x2^2 + 7/5*(1-v^2)x1*x3)/μ^5
    ρ = -6χ₀ / μ^2 - 6χ₁*x1/(γ * μ^4 * T) + 42χ₂*(6//5 *x1^2 + 10γ^2*x2^2 + 3//2*(v^2-1)^2*x3^2)/(μ^5 * γ^2)
    Q = 10χ₀ * x2 * T / μ^3 + 168χ₂ * x2 * (x1 - (v^2 - 1)x3)/(γ * μ^5)

    #flux[1] = 4//3 * ρ*γ^2*v + γ*Q*(1+v^2)+ τ*v
    #flux[2] = 4//3 * ρ*(γ^2*v^2 + 1//4) + 2v*γ*Q + τ
    #flux[3] = χ₁*γ*v*(6*γ^2 - 1)/μ^3/T - 12χ₂*(v*(6γ^2 - 1)*x1 + (6γ^2*(2v^2 + 1)-1)*x2 + v*(v^2+2)*x3)/μ^4
    #flux[4] = χ₁*γ*(6γ^2*v^2+1)/μ^3/T - 12χ₂*((6γ^2*v+1)*x1 + v*(6γ^2*(1+v^2)+1)*x2 + (2v^2+1)*x3)/μ^4
    #flux[5] = 3χ₁*γ*v*(2γ^2*v^2+1)/μ^3/T - 12χ₂*(v*(6γ^2*v^2+3)*x1 +3*(1+6γ^2*v^2)*x2 + 3v*x3)/μ^4
    #return -flux[:]
    return [4//3 * ρ*γ^2*v + γ*Q*(1+v^2)+ τ*v; 
            4//3 * ρ*(γ^2*v^2 + 1//4) + 2v*γ*Q + τ;
            χ₁*γ*v*(6*γ^2 - 1)/μ^3/T - 12χ₂*(v*(6γ^2 - 1)*x1 + (6γ^2*(2v^2 + 1)-1)*x2 + v*(v^2+2)*x3)/μ^4;
            χ₁*γ*(6γ^2*v^2+1)/μ^3/T - 12χ₂*((6γ^2*v+1)*x1 + v*(6γ^2*(1+v^2)+1)*x2 + (2v^2+1)*x3)/μ^4;
            3χ₁*γ*v*(2γ^2*v^2+1)/μ^3/T - 12χ₂*(v*(6γ^2*v^2+3)*x1 +3*(1+6γ^2*v^2)*x2 + 3v*x3)/μ^4]
end

Flux (generic function with 1 method)

Chequeamos con los valores de Marcelo. 

In [3]:
χ = [- 1.; - 2.; - 10.]
flu = [- 5.; 0.5; 2.1; 0.5; 5.1]
Flu = [5.921317694643806; 6.02302807825841; 3.713391378258412;  4.136735467078638; 3.444079555898864]

Flux(flu,χ) - Flu

5-element Vector{Float64}:
  0.0
  8.881784197001252e-16
 -8.881784197001252e-16
  0.0
  4.440892098500626e-16

Calculamos el Jacobiano

In [4]:
@variables f[1:5], c[1:5], p[1:3]#, fl[1:5]

JFS = Symbolics.jacobian(Flux(f,p),f);
JF_exp = Symbolics.build_function(JFS, f, p);
JFac = eval(JF_exp[1]);

Definimos algunos valores para testear

In [52]:
@variables x1, x2, x3

flu=[-1.;0;0;0;0];
con=ones(5)
χ=[-1.,-0.5,-5.]

3-element Vector{Float64}:
 -1.0
 -0.5
 -5.0

El Jacobiano en equilibrio.

In [53]:
JFac(flu,p)

5×5 Matrix{Num}:
  0.0    (-8//1)*p₁          0.0    -10.0p₁      0.0
 -4.0p₁           0.0       -2.0p₂    0.0       -2.0p₂
  0.0            -5.0p₂     -0.0    -60.0p₃     -0.0
 -2.5p₂           0.0    -12p₃       -0.0    -12p₃
  0.0            -3.0p₂     -0.0    -36.0p₃     -0.0

Ahora traemos el Jacobiano de la transformación entre las variables fluido/conservativas.

In [54]:
include("inversion_ext.jl");

Para posterior uso calculamos las variables conservativas correspondientes al estado de equilibrio. Esto no me lo esperaba, pensaba que me darían c1=c2=c3=0!

In [55]:
con = F(flu,zeros(5), p)

5-element Vector{Num}:
 -6.0p₁
  0.0
 -3.0p₂
  0.0
 -3.0p₂

In [56]:
Jac(flu,con,p)

5×5 Matrix{Num}:
 -12.0p₁           0.0       -6.0p₂    0.0        0.0
   0.0    (-8//1)*p₁          0.0    -10.0p₁      0.0
  -7.5p₂          -0.0      -36.0p₃   -0.0        0.0
   0.0           -15.0p₂     -0.0    -60.0p₃     -0.0
  -7.5p₂           0.0    -12p₃       -0.0    -12p₃

In [57]:
P(flu,c,p) = Jac(flu,c,p) \ JFac(flu,p)

P (generic function with 1 method)

In [58]:
P(flu,c,p)

5×5 Matrix{Num}:
                   0.0                                            …                    0.0
 (-1//8)*(p₁^-1)*(50.0p₁*p₂*((18.75p₂ - (60.0p₃))^-1) - (4.0p₁))     (-1//8)*(p₁^-1)*(10.0p₁*(3.75(p₁^-1)*(p₂^2) - (12p₃))*((18.75p₂ - (60.0p₃))^-1) - (2.0p₂))
                   0.0                                                                -0.0
                   5.0p₂*((18.75p₂ - (60.0p₃))^-1)                                    (3.75(p₁^-1)*(p₂^2) - (12p₃))*((18.75p₂ - (60.0p₃))^-1)
                   0.0                                                                -0.0

Miramos primero el caso donde las variables están desacopladas, es decir con $\chi_1=0$.

In [59]:
P(flu,c,[-1,0,-1])

5×5 Matrix{Float64}:
 0.0  0.666667   0.0   0.833333   0.0
 0.5  0.0       -0.25  0.0       -0.25
 0.0  0.0        0.0   1.66667    0.0
 0.0  0.0        0.2   0.0        0.2
 0.0  0.0        0.0   1.33333    0.0

Vemos que se corresponde con la siguiente matriz racional.

In [67]:
M = [0 2//3 0 5//6 0;
    1//2 0 -1//4 0 -1//4;
    0 0 0 5//3 0;
    0 0 1//5 0 1//5;
    0 0 0 4//3 0]

5×5 Matrix{Rational{Int64}}:
 0//1  2//3   0//1  5//6   0//1
 1//2  0//1  -1//4  0//1  -1//4
 0//1  0//1   0//1  5//3   0//1
 0//1  0//1   1//5  0//1   1//5
 0//1  0//1   0//1  4//3   0//1

In [68]:
P(flu,c,[-1,0,-1]) - M

5×5 Matrix{Float64}:
 0.0  0.0  0.0  -1.11022e-16  0.0
 0.0  0.0  0.0   0.0          0.0
 0.0  0.0  0.0  -2.22045e-16  0.0
 0.0  0.0  0.0   0.0          0.0
 0.0  0.0  0.0   0.0          0.0

In [70]:
eigvals(M)

5-element Vector{Float64}:
 -0.7745966692414842
 -0.5773502691896256
  3.0357660829594124e-18
  0.5773502691896258
  0.7745966692414837

In [75]:
1/0.7745966692414837^2 - 5/3

-1.5543122344752192e-15

In [78]:
1/0.5773502691896258^2 - 3

-8.881784197001252e-16

In [79]:
eigvals(P(flu,c,[-1,-0.5,-1]))

5-element Vector{Float64}:
 -0.8013317157511906
 -0.5915355536961237
 -9.375535133588242e-18
  0.5915355536961235
  0.8013317157511908

Hacemos lo mismo para la fuente.

In [80]:
function Is(flu,par)
    χ = par #only used to test otherwise are defined below. a is and amplitude to change I from outside
    μ = flu[1] 
    χ₀= χ[1]
    χ₁= -χ[2] # lo hacemos positivo
    κ = χ₀*μ^5/(15π*χ₁^2) # OK 
    λ = -χ₀*μ^4/(1π*χ₁^2)   # OK
    T = (abs(μ))^(-1//2) # use μ positive, so I changed μ -> -μ
    v = flu[2]
    x1 = flu[3]
    x2 = flu[4]
    x3 = flu[5]
    γ = (1. - v^2)^(-1//2)
    #Is[1] = 0.
    #Is[2] = 0.
    #Is[3] = -2//5*a*(γ^2-1//4)*T*x1/(γ*λ) - 2γ*v*x2/T/κ - v^2*T*x3/(γ*λ)
    #Is[4] = -2//5*a*γ*v*T*x1/λ - γ*(v^2+1)*x2/T/κ - v*T*x3/(γ*λ)
    #Is[5] = -2//5*a*(γ^2*v^2+1//4)*T*x1/λ/γ - 2γ*v*x2/T/κ - T*x3/(γ*λ)
    #return Is[:]      #(1 - ℯ^(-5. *t))
    return [0.;
            0.;
            -2//5*(γ^2-1//4)*T*x1/(γ*λ) - 2γ*v*x2/T/κ - v^2*T*x3/(γ*λ);
            -2//5*γ*v*T*x1/λ - γ*(v^2+1)*x2/T/κ - v*T*x3/(γ*λ);
            -2//5*(γ^2*v^2+1//4)*T*x1/λ/γ - 2γ*v*x2/T/κ - T*x3/(γ*λ)
            ]
end

Is (generic function with 1 method)

La chequeamos con valores de Marcelo.

In [83]:
t=0
flu = [- 5.; 0.5; 2.1; 0.5; 5.1]
par = [-1., -2., -10.]
I_c = [0.; 0.; - 0.09488575328013785; - 0.12155655385334033; - 0.12140081195218293]
Is(flu,par) - I_c

5-element Vector{Float64}:
 0.0
 0.0
 1.3877787807814457e-17
 1.3877787807814457e-17
 1.3877787807814457e-17

In [84]:
Is(f,p)

5-element Vector{Num}:
 0.0
 0.0
 3.141592653589793f₅*(f₁^-4)*(f₂^2)*(p₁^-1)*(p₂^2)*(abs(f₁)^(-1//2))*((1.0 - (f₂^2))^(1//2)) - (94.24777960769379f₂*f₄*(f₁^-5)*(p₁^-1)*(p₂^2)*(abs(f₁)^(1//2))*((1.0 - (f₂^2))^(-1//2))) - (3.141592653589793f₃*(f₁^-4)*(p₁^-1)*(p₂^2)*(abs(f₁)^(-1//2))*((1.0 - (f₂^2))^(1//2))*((1//10) - ((2//5)*((1.0 - (f₂^2))^(-1//1)))))
 1.2566370614359172f₂*f₃*(f₁^-4)*(p₁^-1)*(p₂^2)*(abs(f₁)^(-1//2))*((1.0 - (f₂^2))^(-1//2)) + 3.141592653589793f₂*f₅*(f₁^-4)*(p₁^-1)*(p₂^2)*(abs(f₁)^(-1//2))*((1.0 - (f₂^2))^(1//2)) - (47.12388980384689f₄*(f₁^-5)*(p₁^-1)*(p₂^2)*(abs(f₁)^(1//2))*(1 + f₂^2)*((1.0 - (f₂^2))^(-1//2)))
 3.141592653589793f₅*(f₁^-4)*(p₁^-1)*(p₂^2)*(abs(f₁)^(-1//2))*((1.0 - (f₂^2))^(1//2)) - (94.24777960769379f₂*f₄*(f₁^-5)*(p₁^-1)*(p₂^2)*(abs(f₁)^(1//2))*((1.0 - (f₂^2))^(-1//2))) - (3.141592653589793f₃*(f₁^-4)*(p₁^-1)*(p₂^2)*((-1//10) - ((2//5)*(f₂^2)*((1.0 - (f₂^2))^(-1//1))))*(abs(f₁)^(-1//2))*((1.0 - (f₂^2))^(1//2)))

In [85]:
JSS = Symbolics.jacobian(Is(f,p),f);
JS_exp = Symbolics.build_function(JSS, f, p);
JSac = eval(JS_exp[1]);

In [86]:
flu=[1.;0;0;0;0];
con=ones(5)
JSac(flu,p)

5×5 Matrix{Num}:
 0    0    0                       …  0
 0    0    0                          0
 0.0  0.0  0.942478(p₁^-1)*(p₂^2)     0.0
 0.0  0.0  0.0                        0.0
 0.0  0.0  0.314159(p₁^-1)*(p₂^2)     3.14159(p₁^-1)*(p₂^2)

In [87]:
II(flu,c,p) = Jac(flu,c,p) \ JSac(flu,p)

II (generic function with 1 method)

In [88]:
II(flu,c,p)

5×5 Matrix{Num}:
 0    0    …   0
 0    0        0
 0.0  0.0      0.0
 0.0  0.0      0.0
 0.0  0.0     -0.261799(p₁^-1)*(p₂^2)*(p₃^-1)

In [96]:
par = [-1,-0.5,-10]
eigvals(10*im .* P(flu,c,par) + II(flu,c,par))

5-element Vector{ComplexF64}:
   -0.003948272549998108 - 1.9686487478300475e-16im
 -0.00010115664332310814 + 5.78847409830599im
   -0.000101156643319758 - 5.788474098305988im
    0.008449711345489656 - 7.744246264571347im
    0.008449711345490218 + 7.74424626457135im

Vemos que un par de autovalores tiene parte real positiva. 

In [94]:
eigvecs(II(flu,c,par))

5×5 Matrix{Float64}:
 0.0  0.242536     1.0  0.0  0.0
 0.0  0.0          0.0  1.0  0.780869
 0.0  0.970142     0.0  0.0  0.0
 0.0  0.0          0.0  0.0  0.624695
 1.0  0.000559805  0.0  0.0  0.0

In [26]:
E = eigvecs(10*im .* P(flu,c,par) - II(flu,c,par))

5×5 Matrix{ComplexF64}:
 0.337035-0.000948961im  0.337035+0.000948961im  …    -0.333332+1.47451e-16im
  0.20085+0.00135487im   -0.20085+0.00135487im      2.97604e-16+6.66709e-5im
 0.676377+0.0im          0.676377+0.0im               -0.664928+6.59195e-17im
  0.31675+0.000372305im  -0.31675+0.000372305im     1.15372e-16+0.000132508im
 0.536887-0.000396152im  0.536887+0.000396152im        0.668402+0.0im

In [27]:
E[1,:]

5-element Vector{ComplexF64}:
 0.33703509501333395 - 0.0009489605368876997im
 0.33703509501333356 + 0.0009489605368884178im
   0.764720751926126 + 0.0im
  0.7647207519261257 + 0.0im
 -0.3333322546096297 + 1.474514954580286e-16im

In [28]:
10*im .* P(flu,c,par) - II(flu,c,par)

5×5 Matrix{ComplexF64}:
  0.0-0.0im       0.0-6.66667im    …         0.0-0.0im
 -0.0-5.05291im   0.0+0.0im                  0.0+1.26984im
  0.0+0.0im       0.0+0.0im                  0.0+0.0im
 -0.0-0.042328im  0.0+0.0im                  0.0+2.01587im
  0.0+0.0im       0.0+0.0833333im     0.00654498+0.0im