In [1]:
using Symbolics
using LinearAlgebra
using Latexify
using Plots

In [213]:
include("symbolics_ext.jl")

χ0AB (generic function with 2 methods)

In [86]:
D = Int64(4) #dimensions
#D = Int64(2) #dimensions
L = (D+(D*(D+1)÷2))
#ζ = Vector{Float64}(undef,L)
#ζ_v = Vector{Float64}(undef,D)
#ζ_t = Array{Float64}(undef,D,D)
g = make_g(D)
ζ = rand(L)
p = ([1.0;1.0;1.0])

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [123]:
Φ_new(ζ,p)

11.530697656276184

In [81]:
@variables vs[1:L] ps[1:3]
vst = [vs[i] for i ∈ 1:L]
∇ζ = Symbolics.gradient(Φ_new(vs,ps),vst);

In [82]:
∇ζ_exp = Symbolics.build_function(∇ζ,vs,ps);
∇ζ_f = eval(∇ζ_exp[1])

#83 (generic function with 1 method)

In [83]:
∇ζ_f(ζ,p)

14-element Vector{Float64}:
 -1013.413944186829
 -1459.5371755177612
 -1726.260981488396
 -1344.9209665884164
     0.8416380851338819
    48.23339593671578
    56.444887889252854
    61.32776054950823
    95.32247225550483
   242.975116459748
   184.4064365858252
   167.9871930806561
   258.3515771719864
    83.39737733989757

In [250]:
vs_a = [vs[i] for i ∈ 1:D]
ΦaA = χaA(Φ_new(vs,ps),vs_a,vst);

In [251]:
ΦaA_exp = Symbolics.build_function(ΦaA,vs,ps);
ΦaA_f = eval(ΦaA_exp[1])

#147 (generic function with 1 method)

In [252]:
ΦaA_f(ζ,p)

4×14 Matrix{Float64}:
 210.908   107.215   -96.15      125.203   …    2.55455   0.925487   -6.55264
 107.215   286.538  -406.165     291.03        38.5431   22.7022    -48.2403
 -96.15   -406.165     3.65376  -309.09       -23.8564   28.5717     11.9117
 125.203   291.03   -309.09       68.0756      31.0289   11.5871     13.7742

In [253]:
#include("symbolics_ext.jl")
Φ0AB = χ0AB(Φ_new(vs,ps),vst);

In [254]:
Φ0AB_exp = Symbolics.build_function(Φ0AB,vs,ps);
Φ0AB_f = eval(Φ0AB_exp[1])

#149 (generic function with 1 method)

In [255]:
Φ0AB_f(ζ,p)

14×14 Matrix{Float64}:
  -734.776    -1325.0       779.168    …  -65.051     -55.6182     85.9578
 -1325.0       -384.94      499.832        -7.35521    -6.84646    32.4808
   779.168      499.832     210.558         1.32293   -25.8433     -0.74784
 -1007.15      -760.864     466.342       -11.5001     -1.87132    22.6351
   188.749        6.06373    -4.05027      -1.14475     1.14375     3.10813
    15.3165     343.295     -63.1665   …    7.98105    -8.0314    -21.8826
    -7.72489    -63.1665   -122.491         2.9453     14.231      -2.5776
    44.6295     367.812     -55.6182        7.1155     -5.1552     -4.33241
   167.842      -19.0619     -4.62536      -1.26945     1.70734     5.07907
   -63.1665      -9.62636   -17.8994       -1.22793    -5.86902     1.436
   367.812       16.6731     -6.84646  …   -2.93451     2.872       4.50938
   -65.051       -7.35521     1.32293       1.05654    -1.09476    -0.931845
   -55.6182      -6.84646   -25.8433       -1.09476    -3.72738     0.5

In [257]:
ζ_t = zeros(14)
ζ_t[1] = 1.0  
ζ_t[2] = 0.10
ζ_t[4 + l_ind(1,1,4)] = 1.0 #00
ζ_t[4 + l_ind(1,2,4)] = 0.25 #01
ζ_t[4 + l_ind(2,2,4)] = 0.5 #11
ζ_t[4 + l_ind(3,3,4)] = 0.25
ζ_t[4 + l_ind(4,4,4)] = 0.25

#tr(g*vector_unpack(ζ_t)[2])
#vector_unpack(ζ_t)[2]
println(ζ_t)
println(make_vector_TF!(ζ_t))

[1.0, 0.1, 0.0, 0.0, 1.0, 0.25, 0.0, 0.0, 0.5, 0.0, 0.0, 0.25, 0.0, 0.25]
[1.0, 0.1, 0.0, 0.0, 1.0, 0.25, 0.0, 0.0, 0.5, 0.0, 0.0, 0.25, 0.0, 0.25]


In [258]:

ΦaA_f(ζ_t,p)

4×14 Matrix{Float64}:
 -569.932     16.0507     0.0    …   0.0      40.1761    0.0  40.1761
   16.0507  -204.817      0.0       -0.0      -2.73716  -0.0  -2.73716
    0.0        0.0     -182.557     -0.0       0.0      -0.0   0.0
    0.0        0.0       -0.0       -2.73716   0.0      -0.0   0.0

In [267]:
#T = ΦaA_f(ζ_t,[-1.0,1.0,1.0])[1:D,1:D]
T = ΦaA_f(make_vector_TF!(rand(L)),[-1.0,1.0,1.0])[1:D,1:D]

4×4 Matrix{Float64}:
 18.6432    6.0818   15.0797   17.9213
  6.0818  -29.826     1.55682   7.58679
 15.0797    1.55682  12.0281   45.7031
 17.9213    7.58679  45.7031   36.4411

In [268]:
tr(g*T)

0.0

In [261]:
A0 = vector2symmat(ΦaA_f(ζ_t,[-1.0,1.0,1.0])[1,D+1:end])

4×4 Matrix{Float64}:
 124.185   -14.5102  -0.0     -0.0
 -14.5102   43.8331   0.0      0.0
  -0.0       0.0     40.1761   0.0
  -0.0       0.0      0.0     40.1761

In [262]:
Φ0AB_f(ζ_t,p)

14×14 Matrix{Float64}:
 4523.3    -285.362      0.0     …  -281.665     0.0     -281.665
 -285.362  1634.92       0.0          24.9288    0.0       24.9288
    0.0       0.0     1444.19          0.0       0.0        0.0
    0.0       0.0        0.0           0.0       0.0        0.0
 -876.17    131.812      0.0          31.7353    0.0       31.7353
  263.624  -625.681      0.0     …    -8.84552   0.0       -8.84552
    0.0       0.0     -563.329         0.0      -0.0        0.0
    0.0       0.0       -0.0           0.0      -0.0        0.0
 -312.841    81.9545     0.0           6.75086   0.0        6.75086
    0.0       0.0       49.8576        0.0       0.0        0.0
    0.0       0.0        0.0     …     0.0       0.0        0.0
 -281.665    24.9288     0.0          18.7384    0.0        6.24612
    0.0       0.0        0.0           0.0      24.9845     0.0
 -281.665    24.9288     0.0           6.24612   0.0       18.7384

In [263]:
@time Φ0AB_f(ζ_t,p)[6,1]

  0.000675 seconds (399 allocations: 11.016 KiB)


263.62421706993825

In [265]:
#AA = get_A(ΦaA_f(ζ_t,[-1.0,1.0,1.0]))
AA = get_A(ΦaA_f(make_vector_TF!(rand(L)),[-1.0,1.0,1.0]))

4×4×4 Array{Float64, 3}:
[:, :, 1] =
  6.39553e7  -4.92528e7  -2.86083e7  -3.12133e7
 -4.92528e7   3.7523e7    2.23816e7   2.4408e7
 -2.86083e7   2.23816e7   1.19599e7   1.41821e7
 -3.12133e7   2.4408e7    1.41821e7   1.44725e7

[:, :, 2] =
 -4.92528e7   3.7523e7    2.23816e7   2.4408e7
  3.7523e7   -2.82437e7  -1.73368e7  -1.88945e7
  2.23816e7  -1.73368e7  -9.50981e6  -1.12696e7
  2.4408e7   -1.88945e7  -1.12696e7  -1.14993e7

[:, :, 3] =
 -2.86083e7   2.23816e7   1.19599e7   1.41821e7
  2.23816e7  -1.73368e7  -9.50981e6  -1.12696e7
  1.19599e7  -9.50981e6  -4.5822e6   -6.02612e6
  1.41821e7  -1.12696e7  -6.02612e6  -6.68926e6

[:, :, 4] =
 -3.12133e7   2.4408e7    1.41821e7   1.44725e7
  2.4408e7   -1.88945e7  -1.12696e7  -1.14993e7
  1.41821e7  -1.12696e7  -6.02612e6  -6.68926e6
  1.44725e7  -1.14993e7  -6.68926e6  -6.29266e6

In [266]:
full_symmetry_check(AA)

5.774199962615967e-8

In [270]:
include("symbolics_ext.jl")
tr_A_12(AA,g)

4-element Vector{Float64}:
  1.862645149230957e-9
  5.587935447692871e-9
 -7.450580596923828e-9
  5.587935447692871e-9

In [227]:
tr(g*AA[:,:,1])

8.881784197001252e-16

In [244]:
AA[1,1,2]

-2.9862036909702994