In [37]:
include("inversion_ext.jl")

 Activating environment at `~/Julia/Fluidos_Conformes/Conf_Fluids/Project.toml`
  Resolving package versions...
No Changes to `~/Julia/Fluidos_Conformes/Conf_Fluids/Project.toml`
No Changes to `~/Julia/Fluidos_Conformes/Conf_Fluids/Manifest.toml`


c_to_f_direct! (generic function with 1 method)

## Checking f_to_c

In [38]:
N=10
M=1
χ = [-1.0; -1.0; -5.0]
p = (χ, N, M)
u = zeros(N*M)
u0 = zeros(N*M)

con = view(reshape(u,(M,N)),:,1:5)
flu = view(reshape(u,(M,N)),:,6:10)

flu[1,:] = [-10.0, 0.2, 1.1, 1.5, 1.2]
con[1,:] = [0.1366314976448222, 0.07009306769467444, 0.06115332989597844, 0.07178418128379448, 0.04927907295689818]

con0 = view(reshape(u0,(M,N)),:,1:5)
flu0 = view(reshape(u0,(M,N)),:,6:10)

flu0[1,:] = [-10.0, 0.2, 1.1, 1.5, 1.2]
#con0[1,:] = [0.1366314976448222, 0.07009306769467444, 0.06115332989597844, 0.07178418128379448, 0.04927907295689818]

println(u0)
println(u)
println(f_to_c!(u0,p) - u)
println(u0)

[0.0, 0.0, 0.0, 0.0, 0.0, -10.0, 0.2, 1.1, 1.5, 1.2]
[0.1366314976448222, 0.07009306769467444, 0.06115332989597844, 0.07178418128379448, 0.04927907295689818, -10.0, 0.2, 1.1, 1.5, 1.2]
[0.0, -1.3877787807814457e-17, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.1366314976448222, 0.07009306769467442, 0.06115332989597844, 0.07178418128379448, 0.04927907295689818, -10.0, 0.2, 1.1, 1.5, 1.2]


In [39]:
tol = 10^(-16)
iter_max = 40
χ = [-1.0; -1.0; -5.0]
M=1
N=10
p = (χ, tol, iter_max, N, M)

u = zeros(N*M)
u0 = zeros(N*M)

con = view(reshape(u,(M,N)),:,1:5)
flu = view(reshape(u,(M,N)),:,6:10)

flu[1,:] = [-10.0, 0.2, 1.1, 1.5, 1.2]
con[1,:] = [0.1366314976448222, 0.07009306769467444, 0.06115332989597844, 0.07178418128379448, 0.04927907295689818]

con0 = view(reshape(u0,(M,N)),:,1:5)
flu0 = view(reshape(u0,(M,N)),:,6:10)

flu0[1,:] = [-10.0, 0.2, 1.1, 1.5, 1.2] + 0.01 .*rand(N÷2)
con0[1,:] = [0.1366314976448222, 0.07009306769467444, 0.06115332989597844, 0.07178418128379448, 0.04927907295689818]

5-element Array{Float64,1}:
 0.1366314976448222
 0.07009306769467444
 0.06115332989597844
 0.07178418128379448
 0.04927907295689818

In [40]:
@time c_to_f!(u0, p) - u

  0.292044 seconds (1.08 M allocations: 45.334 MiB, 8.01% gc time)


10-element Array{Float64,1}:
  0.0
  0.0
  0.0
  0.0
  0.0
  3.3650164255050186e-7
  5.300992977907981e-11
 -1.3363915640773882e-7
 -2.0150819324271652e-7
  6.993196866034168e-8

## Testing with Euler

In [41]:
N=10
M=1
χ = [-1.0; 0.0; -1.0] #put the interaction term to zero
p = (χ, N, M)
u = zeros(N*M)
u0 = zeros(N*M)

con0 = view(reshape(u0,(M,N)),:,1:5)
flu0 = view(reshape(u0,(M,N)),:,6:10)
con = view(reshape(u,(M,N)),:,1:5)
flu = view(reshape(u,(M,N)),:,6:10)

flu0[1,:] = [-10.0, 0.2, 0., 0., 0.]
flu[1,:] = [-10.0, 0.2, 0., 0., 0.]
#flu0[1,:] = [-10.0, 0.2, 1.1, 1.5, 1.2]

println(f_to_c!(u0,p))

[0.06333333333333332, 0.016666666666666666, 0.0, 0.0, 0.0, -10.0, 0.2, 0.0, 0.0, 0.0]


In [42]:
flu[1,1] = -flu[1,1]
con[1,:] = F(flu,con,χ)
flu[1,1] = -flu[1,1];
u

10-element Array{Float64,1}:
   0.06333333333333332
   0.016666666666666666
   0.0
   0.0
   0.0
 -10.0
   0.2
   0.0
   0.0
   0.0

In [45]:
con0 = view(reshape(u0,(M,N)),:,1:5)
flu0 = view(reshape(u0,(M,N)),:,6:10)

flu0[1,:] = [-10.0, 0.2, 0,0,0]

println(u0)
println(u)
println(f_to_c!(u,p) - u)
println(u0)

[0.06333333333333332, 0.016666666666666666, 0.0, 0.0, 0.0, -10.0, 0.2, 0.0, 0.0, 0.0]
[0.1366314976448222, 0.07009306769467444, 0.06115332989597844, 0.07178418128379448, 0.04927907295689818, -10.0, 0.2, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.06333333333333332, 0.016666666666666666, 0.0, 0.0, 0.0, -10.0, 0.2, 0.0, 0.0, 0.0]


In [46]:
@time c_to_f_direct!(u0,p) - u

  0.000026 seconds (6 allocations: 512 bytes)


10-element Array{Float64,1}:
  0.0
  0.0
  0.0
  0.0
  0.0
 -1.7763568394002505e-15
  0.0
  0.0
  0.0
  0.0