In [1]:
include("Flux_function_ext.jl")

Speed_max (generic function with 1 method)

In [2]:
χ = [- 1.; - 2.; - 10.]
flu = [0.;0.;0.;0.;0.;- 5.; 0.5; 2.1; 0.5; 5.1]
Flu = [5.921317694643806; 6.02302807825841; 3.713391378258412;  4.136735467078638; 3.444079555898864; 0.;0.;0.;0.;0.]

@time Flux(flu,χ) + Flu # this are the correct signs so that the flux has the correct expression on the mp5

  0.284062 seconds (793.05 k allocations: 47.065 MiB, 6.07% gc time, 99.96% compilation time)


10-element Vector{Float64}:
  0.0
 -8.881784197001252e-16
  8.881784197001252e-16
  0.0
 -4.440892098500626e-16
  0.0
  0.0
  0.0
  0.0
  0.0

In [3]:
χ = [- 1.; - 2.; - 10.]
flu = [0.;0.;0.;0.;0.;- 5.; 0.5; 2.1; 0.5; 5.1]
Flu = [5.921317694643806; 6.02302807825841; 3.713391378258412;  4.136735467078638; 3.444079555898864; 0.;0.;0.;0.;0.]
F = zeros(10)
@time Flux!(F,flu,χ) + Flu

  0.068470 seconds (262.27 k allocations: 15.908 MiB, 24.23% gc time, 99.96% compilation time)


10-element Vector{Float64}:
  0.0
 -8.881784197001252e-16
  8.881784197001252e-16
  0.0
 -4.440892098500626e-16
  0.0
  0.0
  0.0
  0.0
  0.0

In [4]:
t=0
par = ([-1., -2., -10.], [1/15π, 1/1π, 1])
I_c = [0.; 0.; - 0.09488575328013785; - 0.12155655385334033; - 0.12140081195218293; 0.;0.;0.;0.;0.]
@time Is(flu,t,par) - I_c

  0.110966 seconds (396.11 k allocations: 23.780 MiB, 99.90% compilation time)


10-element Vector{Float64}:
 0.0
 0.0
 1.3877787807814457e-17
 1.3877787807814457e-17
 1.3877787807814457e-17
 0.0
 0.0
 0.0
 0.0
 0.0

In [5]:
t=0
par = ([-1., -2., -10.], [1/15π, 1/1π, 1])
S = zeros(10)
I_c = [0.; 0.; - 0.09488575328013785; - 0.12155655385334033; - 0.12140081195218293; 0.;0.;0.;0.;0.]
@time Is!(S,flu,t,par) 
S - I_c

  0.063670 seconds (162.21 k allocations: 10.210 MiB, 20.28% gc time, 99.96% compilation time)


10-element Vector{Float64}:
 0.0
 0.0
 1.3877787807814457e-17
 1.3877787807814457e-17
 1.3877787807814457e-17
 0.0
 0.0
 0.0
 0.0
 0.0