### Symbolic treatment of the fluid equations

In this notebook we obtain the equations, and all relevant quantities starting from the generating function and in arbitrary dimensions. 
We spacialize for the conformal case, but this is not needed. 

We use a flat, constant metric, but it is not difficult to add an arbitrary metric latter on, even curvature.

$$
T^{ab} = \frac{\partial^2 \chi}{\zeta_a \zeta_b}
$$

$$
A^{abc} = \frac{\partial^2 \chi}{\zeta_a \zeta_{bc}}
$$

In our case the conformally invariant $\chi$ is given by:

$$
\chi(\zeta_a, \zeta_{ab}) = \chi_0 \mu^{-d/2 + 1} + \chi_1 \nu \mu^{-d/2 -1} 
+ \chi_2(\tau_2 - \frac{4(d/2+1)}{\mu} \omicron + \frac{2(d/2+1)(d/2+2)}{\mu^2}\nu^2)\mu^{-d/2 -1},
$$

where,

$$
\mu := \zeta^a \zeta_a \;\;\;\;\;\;\;\;  \nu := \zeta_{ab}\zeta^a \zeta^b \;\;\;\;\;\;\;\; \omicron := \zeta^a \zeta_{ab} \zeta^{bc} \zeta_c, \;\;\;\;\;\;\;\; \tau_2  := \zeta_{ab}\zeta^{ab}
$$



We define a vector $v_A$ with all the components with the following scheme:

$$
\zeta_a = [v_1, v_2, v_3,  v_4]
$$

$$
\zeta_{ab} = \left(
                \begin{array}{llll}
                v_5 & v_6 & v_7 & v_8 \\
                v_6 & v_9 & v_{10} & v_{11} \\
                v_7 & v_{10} & v_{12} & v_{13} \\ 
                v_8 & v_{11} & v_{13} & v_{14}
                \end{array}
            \right)
$$

Thus, for the case with planar symmetry the only non-zero components are: $\{v_1, v_2, v_5, v_6, v_9\}$


In [2]:
using Symbolics
using LinearAlgebra
using Latexify
using Plots

In [3]:
include("symbolics_ext.jl")

χaAB (generic function with 1 method)

The variables are going to be a vector-tensor $\zeta_A = (\zeta_a, \zeta_{ab})$ with the tensor part being symmetric and (latter) trace free. We are going to use both representations, either a big vector or a pair vector-tensor.
With functions going from one to the other.

We first define some tensors and take a symmetrize them using the upper triangular part as the relevant tensor part, contrary to take the average of the components

In [4]:
D = Int64(4) #dimensions
#D = Int64(2) #dimensions
L = (D+(D*(D+1)÷2))
ζ = Vector{Float64}(undef,L)
ζ_v = Vector{Float64}(undef,D)
ζ_t = Array{Float64}(undef,D,D)
g = make_g(D)

4×4 Matrix{Float64}:
 -1.0  0.0  0.0  0.0
  0.0  1.0  0.0  0.0
  0.0  0.0  1.0  0.0
  0.0  0.0  0.0  1.0

In [5]:
v = [1;2;3;4;5;6]
sm = zeros(3,3)

vector2symmat!(v,sm)
sm

3×3 Matrix{Float64}:
 1.0  2.0  3.0
 2.0  4.0  5.0
 3.0  5.0  6.0

In [6]:
symmat2vector(sm)

6-element Vector{Float64}:
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0

In [7]:
vector_unpack(rand(L))

([0.48883608498333475, 0.5973167993669481, 0.7757670545613324, 0.5192571733202829], [0.6219854249743013 0.3346909420372537 0.8013387839764619 0.8686126963505936; 0.3346909420372537 0.5645879175363324 0.18921500750998732 0.5144673630901524; 0.8013387839764619 0.18921500750998732 0.6023126933910853 0.3009508282052762; 0.8686126963505936 0.5144673630901524 0.3009508282052762 0.8864633851652357])

In [9]:
v = [1;2;3;4;5;6;7;8;9;10;11;12;13;14]
vector_unpack(v)[2]

4×4 Matrix{Float64}:
 5.0   6.0   7.0   8.0
 6.0   9.0  10.0  11.0
 7.0  10.0  12.0  13.0
 8.0  11.0  13.0  14.0

In [11]:
ζ_t = rand(D,D)
println(tr(ζ_t'*g'*g*ζ_t))



ζ_v = rand(D)
#ζ_v = [0.; 0.; 0.; 0.]

upper2symm!(ζ_t)

Tr = tr(g*ζ_t)
ζ_t = ζ_t - Tr*g/D

@show latexify(ζ_t)

tr(g*ζ_t)

6.248707813985167
latexify(ζ_t) = L"\begin{equation}
\left[
\begin{array}{cccc}
0.9566160672410133 & 0.42197331769817925 & 0.7755164837703081 & 0.568761449514493 \\
0.42197331769817925 & 0.39057473260195824 & 0.6727529400477824 & 0.6772432748258491 \\
0.7755164837703081 & 0.6727529400477824 & 0.12253756828362333 & 0.031956641939618446 \\
0.568761449514493 & 0.6772432748258491 & 0.031956641939618446 & 0.4435037663554318 \\
\end{array}
\right]
\end{equation}
"


0.0

In [13]:
v_test = [2, 1, 0, 0, 3, 4, 0, 0, 5, 0, 0, 0, 0, 0] #vector to test the plane symmetric case.

vector_unpack(v_test)[2]

4×4 Matrix{Float64}:
 3.0  4.0  0.0  0.0
 4.0  5.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

Likewise we define functions which take either a long vector or the pair vector-tensor

In [ ]:
function Φ_vt(ζ_v, ζ_s, p)
    D = length(ζ_v)
    g = make_g(D)
    #println(g)
    χ₀ = p[1]
    χ₁ = p[2]
    χ₂ = p[3]
    #ζ_s = my_symmetrization!(Symbolics.scalarize(ζ_t))
    μ = Symbolics.scalarize(ζ_v)'*g*Symbolics.scalarize(ζ_v)
    ν = (g*Symbolics.scalarize(ζ_v))'*Symbolics.scalarize(ζ_s)*Symbolics.scalarize(g*ζ_v)
    l = Symbolics.scalarize(ζ_s)*Symbolics.scalarize(g*ζ_v)
    𝚶 = l'* g * l
    τ₂= tr(Symbolics.scalarize(ζ_s)*g'*Symbolics.scalarize(ζ_s)*g)
    D1 = D//2+1
    D2 = D//2+2
    return χ₀*μ^(1-D//2) + χ₁*ν*μ^(-D1) + χ₂*(τ₂ - 4*D1*𝚶*μ^(-1) + 2*D1*D2*ν^2*μ^(-2))*μ^(-D1) 
    # the function seems to be correct: tr(g*T)=0 and also A is fully symmetric after symmetrization 
    # on first two indices
    #return 𝚶
end

function Φ_v(ζ,p)
    ζ_v, ζ_t = vector_unpack(ζ)
    #ζ_t = vector2symmat(ζ[D+1:end])
    #return Φ_vt(ζ[1:D], ζ_t, p)
    return Φ_vt(ζ_v, ζ_t, p)
end

ζ_v,ζ_t = vector_unpack(v)
Φ_vt(ζ_v,ζ_t, [1.,1.,1.])#, ζ_t, [1.;1;1])
Φ_v(v, [1.,1.,1.])
#ζ_v
#ζ_t

In [ ]:
@variables zv[1:D], zs[1:D,1:D], pv[1:3]

Φ_vt(zv, zs, pv);

In [ ]:
zvt = [zv[i] for i ∈ 1:D]
zst = vec([zs[i,j] for i ∈ 1:D, j ∈ 1:D])
JΦ_v = Symbolics.gradient(Φ_vt(zv, zs, pv), zvt);
JΦ_s = (reshape(Symbolics.gradient(Φ_vt(zv, zs, pv), zst), (D,D)) + reshape(Symbolics.gradient(Φ_vt(zv, zs, pv), zst), (D,D))')/2 ;

In [ ]:
JΦ_v_exp = Symbolics.build_function(JΦ_v,zv, zs, pv);
JΦ_ve = eval(JΦ_v_exp[1]);
JΦ_ve(ζ_v,ζ_t, pv)

In [ ]:
JΦ_s_exp = Symbolics.build_function(JΦ_s, zv, zs, pv);
JΦ_se = eval(JΦ_s_exp[1]);
JΦ_se(ζ_v, ζ_t, pv);

In [ ]:
T_s = Symbolics.jacobian(JΦ_ve(zv, zs, pv), zvt);

In [ ]:
T_exp = Symbolics.build_function(T_s, zv, zs, pv);
T = eval(T_exp[1]);

In [ ]:
tr(g*T(ζ_v, ζ_t, [1.0;1.0;1.0]))

In [ ]:
tr(g*ζ_t)

In [ ]:
A_s = Symbolics.jacobian(JΦ_ve(zv, zs, pv), zst);

In [ ]:
A_exp = Symbolics.build_function(A_s, zv, zs, pv);
A = eval(A_exp[1]);

In [ ]:
A_val = A(ζ_v, ζ_t, [1.0;1.0;1.0]);

In [ ]:
AA = reshape(A_val', (D,D,D)); # last index is the vectorial one

In [ ]:
AS = symm_A(AA)

In [ ]:
tr_A(AS,g)

In [ ]:
tr_A(STF_A(AS,g),g)

In [ ]:
A_stf = STF_A(AS,g)

In [ ]:
full_symmetry_check(A_stf)

In [ ]:
A_s_dual = Symbolics.jacobian(JΦ_se(zv, zs, pv), zvt);

We define now the conserved quantities and then the field-coordinate transformation.

In [ ]:
function C(ζ,p,g,k::Int64) 
    D = length(Symbolics.scalarize(g)[:,1])
    ζ_v, ζ_t = Symbolics.scalarize(vector_unpack(ζ))
        AA = reshape(Symbolics.scalarize(A(ζ_v, ζ_t, p))', (D,D,D))[:,:,k]
        upper2symm!(AA)
        Tr = tr(AA)
        AA = AA - g*Tr/D
        return [T(ζ_v, ζ_t, p)[:,k]; symmat2vector(AA)]
end

In [ ]:
@variables zz[1:D+D*(D+1)÷2] gv[D,D]
zzt = [zz[i] for i ∈ 1:(D+D*(D+1)÷2)]
JC1_s = Symbolics.jacobian(C(zz,pv,gv,1),zzt)

In [ ]:
C1 = C(rand(14),[1;1;2],g,1)

In [ ]:
T0, A0 = vector_unpack(C1)

In [ ]:
full_symmetry_check(A0)

In [ ]:
function C2A!(ζ,c,p)
    χ, tol, iter_max, g, M, C, J = p
    while norm(C(ζ,χ,g,1) - c) > tol && iter < iter_max
            ζ = ζ - J(ζ,p,g) \ (C(ζ,χ,g,1) - c)
            iter = iter + 1
            if iter == iter_max 
            println("iter_max reached j = $j")
            end
    end
end

In [ ]:
p_N = [1.,1.,1.], 10^(-6), g, 1, C1, JC1

In [ ]:
function c_to_f!(flu, con, p)
    χ, tol, iter_max, N, M = p
    for j ∈ 1:M
        flu[1,j] = -flu[1,j]
        iter = 1
        while F(flu[:,j],con[:,j], χ)'*F(flu[:,j],con[:,j], χ) > tol && iter < iter_max
            flu[:,j] = NR_step!(F, Jac, flu[:,j], con[:,j], χ)
            iter = iter + 1
            if iter == iter_max 
            println("iter_max reached j = $j")
            end
        end
    #println(iter)
        flu[1,j] = -flu[1,j]
    end
    return flu[:,:]
end


In [ ]:
include("symbolics_ext.jl")

Φ_new(rand(L),([1.0;1.0;1.0],make_g(D)))

In [ ]:
@variables vs[1:L] ps[1:3] gs[D,D]
vst = [vs[i] for i ∈ 1:L]
pv = (ps, gs)
∇ζ = Symbolics.gradient(Φ_new(vs,pv),vst);

In [ ]:
∇ζ_exp = Symbolics.build_function(∇ζ,vs,pv);
∇ζ_f = eval(∇ζ_exp[1]);

In [ ]:
g = make_g(D)
pp = ([1.0;1.0;1.0],g)
∇ζ_f(rand(L),([1.0;1.0;1.0],make_g(D)))

In [ ]:
Symbolics.jacobian(∇ζ(vs,pv),vst);

In [ ]:
ζ_v, ζ_t = vector_unpack(vs)
#ζ_v' * gs * ζ_v

#typeof(ζ_v)

In [ ]:
Symbolics.scalarize(vs)[1:D]

In [ ]:
vector2symmat(Symbolics.scalarize(vs)[D+1:end])[:,:]

In [ ]:
include("symbolics_ext.jl")
mu(rand(14))
nu(rand(14))
omicron(rand(14))
tau2(rand(14))