In [275]:
using Symbolics
using LinearAlgebra
using Latexify
using Plots

In [308]:
include("symbolics_ext.jl")

χ0AB

In [309]:
#D = Int64(4) #dimensions
#D = Int64(3)
D = Int64(2) #dimensions
L = (D+(D*(D+1)÷2))
println("D = $D, L = $L")
#ζ = Vector{Float64}(undef,L)
#ζ_v = Vector{Float64}(undef,D)
#ζ_t = Array{Float64}(undef,D,D)
g = make_g(D)
ζ = rand(L)
p = ([1.0;1.0;1.0])

D = 2, L = 5


3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [310]:
Φ_new(ζ,p)

41.5120582824191

In [311]:
@variables vs[1:L] ps[1:3]
vst = [vs[i] for i ∈ 1:L]
∇ζ = Symbolics.gradient(Φ_new(vs,ps),vst);

In [312]:
∇ζ_exp = Symbolics.build_function(∇ζ,vs,ps);
∇ζ_f = eval(∇ζ_exp[1])

#177 (generic function with 1 method)

In [313]:
∇ζ_f(ζ,p)

5-element Vector{Float64}:
 -281.69315273192694
  -86.21383200200704
   25.365037300869652
   86.37387106202348
  -16.498208767777207

In [314]:
vs_a = [vs[i] for i ∈ 1:D]
ΦaA = χaA(Φ_new(vs,ps),vs_a,vst);

In [315]:
ΦaA_exp = Symbolics.build_function(ΦaA,vs,ps);
ΦaA_f = eval(ΦaA_exp[1])

#181 (generic function with 1 method)

In [316]:
ΦaA_f(ζ,p)

2×5 Matrix{Float64}:
 2447.84    405.139    22.8391  -316.401     22.8391
  405.139  2166.51   -321.921     59.6381  -321.921

In [317]:
#include("symbolics_ext.jl")
Φ0AB = χ0AB(Φ_new(vs,ps),vst);

In [318]:
Φ0AB_exp = Symbolics.build_function(Φ0AB,vs,ps);
Φ0AB_f = eval(Φ0AB_exp[1])

#183 (generic function with 1 method)

In [319]:
Φ0AB_f(ζ,p)

5×5 Matrix{Float64}:
 -25914.0      -650.807  -677.701   2961.07   -677.701
   -650.807  -23215.5    3021.04   -1012.32   3021.04
   -677.701    3021.04   -286.525    182.966  -286.525
   2961.07    -1012.32    182.966   -286.525   182.966
   -677.701    3021.04   -286.525    182.966  -286.525

In [320]:
ζ_t = zeros(L)
ζ_t[1] = 1.0  
ζ_t[2] = 0.10
ζ_t[D + l_ind(1,1,D)] = 1.0 #00
ζ_t[D + l_ind(1,2,D)] = 0.25 #01
ζ_t[D + l_ind(2,2,D)] = 0.5 #11
#ζ_t[D + l_ind(3,3,D)] = 0.25
#ζ_t[D + l_ind(4,4,D)] = 0.25

#tr(g*vector_unpack(ζ_t)[2])
#vector_unpack(ζ_t)[2]
println(ζ_t)
println(make_vector_TF!(ζ_t))
tr(g*vector_unpack(ζ_t)[2])

[1.0, 0.1, 1.0, 0.25, 0.5]
[1.0, 0.1, 0.75, 0.25, 0.75]


0.0

In [321]:

ΦaA_f(ζ_t,p)

2×5 Matrix{Float64}:
 64.3678    5.81421  -18.6736     3.02021  -18.6736
  5.81421  64.3678     3.02021  -18.6736     3.02021

In [322]:
T = ΦaA_f(ζ_t,[-1.0,1.0,1.0])[1:D,1:D]
#T = ΦaA_f(make_vector_TF!(rand(L)),[-1.0,1.0,1.0])[1:D,1:D]

2×2 Matrix{Float64}:
 68.4899    4.99797
  4.99797  68.4899

In [323]:
tr(g*T)

8.526512829121202e-14

In [324]:
A0 = vector2symmat(ΦaA_f(ζ_t,[-1.0,1.0,1.0])[1,D+1:end])

2×2 Matrix{Float64}:
 -18.6736     3.02021
   3.02021  -18.6736

In [325]:
Φ0AB_f(ζ_t,p)

5×5 Matrix{Float64}:
 -386.271       4.89986   93.6295   -23.8436    93.6295
    4.89986  -386.271    -23.8436    93.6295   -23.8436
   93.6295    -23.8436   -13.8866     6.43552  -13.8866
  -23.8436     93.6295     6.43552  -13.8866     6.43552
   93.6295    -23.8436   -13.8866     6.43552  -13.8866

In [327]:
@time Φ0AB_f(ζ_t,p)[1,1]

  0.000017 seconds (27 allocations: 672 bytes)


-386.27055961394495

In [328]:
#AA = get_A(ΦaA_f(ζ_t,[-1.0,1.0,1.0]))
AA = get_A(ΦaA_f(make_vector_TF!(rand(L)),[-1.0,1.0,1.0]))

2×2×2 Array{Float64, 3}:
[:, :, 1] =
  345.441  -350.34
 -350.34    345.441

[:, :, 2] =
 -350.34    345.441
  345.441  -350.34

In [329]:
full_symmetry_check(AA)

1.1368683772161603e-13

In [330]:
include("symbolics_ext.jl")
tr_A_12(AA,g)

2-element Vector{Float64}:
 0.0
 0.0

In [331]:
tr(g*AA[:,:,1])

0.0

In [332]:
AA[1,1,2]

-350.34004807719526