## 4D equations using symbolics.

In [1]:
using Symbolics
using LinearAlgebra
using Latexify
using Plots
using BenchmarkTools
using FileIO
using JLD2
using Base.Threads
#Pkg; Pkg.add("DistributedArrays")
println("nthreads = $(nthreads())")
using Printf

nthreads = 10


In [2]:
include("symbolics_ext.jl")

χaAB (generic function with 1 method)

In [3]:
D = Int64(4) #dimensions
L = (D+(D*(D+1)÷2))
println("D = $D, L = $L")
g = make_g(D)
ζ = rand(L)
p = ([1.0;1.0;1.0])

D = 4, L = 14


3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [ ]:
@variables vs[1:L] ps[1:3]
vst = [vs[i] for i ∈ 1:L]
vs_a = [vs[i] for i ∈ 1:D]
ΦaA = χaA(Φ_new(vs,ps),vs_a,vst);
ΦaA_exp = Symbolics.build_function(ΦaA,vs,ps);
ΦaA_f = eval(ΦaA_exp[1])

In [4]:
v_test = [zeros(L) for _ in 1:8]
v_test[1] = [2, 1, 0, 0, 3, 4, 0, 0, 5, 0, 0, 0, 0, 0]
v_test[2] = [4, 2, 0, 0, 3, 4, 0, 0, 5, 0, 0, 0, 0, 0] # para probar μ
v_test[3] = [2, 1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0] # ν
v_test[4] = [2, 1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0] # r
v_test[5] = [2, 1, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0] # τ
v_test[6] = [2, 1, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0] # ν, r
v_test[7] = [2, 1, 0, 0, 3, 0, 0, 0, 5, 0, 0, 0, 0, 0] # ν, τ
v_test[8] = [2, 1, 0, 0, 0, 4, 0, 0, 5, 0, 0, 0, 0, 0] # r, τ

14-element Vector{Int64}:
 2
 1
 0
 0
 0
 4
 0
 0
 5
 0
 0
 0
 0
 0

In [5]:
F_test = [zeros(D,L) for _ in 1:8]

p_test = ([-1.0;1.0;-1.0])

3-element Vector{Float64}:
 -1.0
  1.0
 -1.0

In [ ]:
for i in 1:8
    F_test[i] = ΦaA_f(v_test[i],p_test)
end

In [ ]:
test = Dict("pars" => p_test, "v_test" => v_test, "F_test" => F_test)
file_name = "D4_test" * ".jld2"
#rm(file_name)


save(file_name, test)